services:
  chroma:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - /data/chroma:/data
    networks:
      - internal

  ai-chat-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-chat-server
    container_name: ai-chat-server
    ports:
      - "8100:8100"
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - HF_HOME=/data/huggingface
      - HF_HUB_CACHE=/data/huggingface/hub
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    volumes:
      - /data/huggingface:/data/huggingface
    networks:
      - internal
    depends_on:
      - chroma

networks:
  internal: