from ai_chat.intent.models import Domain

intents: list[tuple[str, Domain]] = [
    # EMPLOYMENT
    ("Where did he work in 2015?", Domain.EMPLOYMENT),
    ("Where did he work from 2015 to 2016?", Domain.EMPLOYMENT),
    ("Where was he employed in the period from 2009 to 2012", Domain.EMPLOYMENT),
    ("What was he doing in 2025?", Domain.EMPLOYMENT),
    ("Which company did he work for in 2015?", Domain.EMPLOYMENT),
    ("Who employed him in 2017?", Domain.EMPLOYMENT),
    ("What job did he have in 2018?", Domain.EMPLOYMENT),
    ("Where was he working during 2019?", Domain.EMPLOYMENT),
    ("Which employer did he have in 2020?", Domain.EMPLOYMENT),
    ("What company was he working at in 2021?", Domain.EMPLOYMENT),
    ("What companies did he work for in 2015?", Domain.EMPLOYMENT),
    ("Which employers did he have in 2018?", Domain.EMPLOYMENT),
    ("What companies did he work for between 2013 and 2014?", Domain.EMPLOYMENT),
    ("List the companies he worked for in 2016.", Domain.EMPLOYMENT),
    ("Which companies employed him during 2011?", Domain.EMPLOYMENT),
    ("Where did he work between 2009 and 2012?", Domain.EMPLOYMENT),
    ("What employers did he have in 2020?", Domain.EMPLOYMENT),
    ("Show the companies he worked for during 2017.", Domain.EMPLOYMENT),
    ("Which organizations did he work for from 2014 to 2016?", Domain.EMPLOYMENT),
    ("Give me the companies he worked for in 2019.", Domain.EMPLOYMENT),
    ("Give me all his employers.", Domain.EMPLOYMENT),
    ("List all his employers.", Domain.EMPLOYMENT),
    ("What companies did he work for?", Domain.EMPLOYMENT),
    ("Summarize his employment history.", Domain.EMPLOYMENT),
    ("Give me an overview of his career.", Domain.EMPLOYMENT),
    ("What does his work history look like?", Domain.EMPLOYMENT),
    ("Describe his professional career.", Domain.EMPLOYMENT),
    ("Can you summarize the companies he worked for?", Domain.EMPLOYMENT),
    ("Provide a summary of his professional background.", Domain.EMPLOYMENT),
    ("What is the overall timeline of his employment?", Domain.EMPLOYMENT),
    ("Explain his career path.", Domain.EMPLOYMENT),
    ("Give a short summary of his work experience.", Domain.EMPLOYMENT),
    ("How has his career developed over the years?", Domain.EMPLOYMENT),
    ("What did he do in Netconomy", Domain.EMPLOYMENT),
    ("What was his role in IBM?", Domain.EMPLOYMENT),

    # SKILLS
    ("Does he know Java?", Domain.SKILLS),
    ("Is he experienced with Spring Boot?", Domain.SKILLS),
    ("Does he have experience with Camunda?", Domain.SKILLS),
    ("Is Kubernetes one of his skills?", Domain.SKILLS),
    ("Does he work with Microservices?", Domain.SKILLS),
    ("Has he used Maven?", Domain.SKILLS),
    ("Does he have experience with Junit framework?", Domain.SKILLS),
    ("Is he familiar with TDD?", Domain.SKILLS),
    ("Has he worked with Android?", Domain.SKILLS),
    ("What skills does he have?", Domain.SKILLS),
    ("Which technologies does he know?", Domain.SKILLS),
    ("List his programming skills.", Domain.SKILLS),
    ("What technologies has he worked with?", Domain.SKILLS),
    ("Which programming languages does he use?", Domain.SKILLS),
    ("Give me a list of his technical skills.", Domain.SKILLS),
    ("What frameworks is he experienced with?", Domain.SKILLS),
    ("What tools does he use as a developer?", Domain.SKILLS),
    ("Which software technologies does he work with?", Domain.SKILLS),
    ("What are his main development skills?", Domain.SKILLS),
    ("What technologies did he use?", Domain.SKILLS),

    # PROFILE
    ("Who is he?", Domain.PROFILE),
    ("Give me a summary of his profile.", Domain.PROFILE),
    ("Tell me about this person.", Domain.PROFILE),
    ("What is his professional profile?", Domain.PROFILE),
    ("Provide an overview of his background.", Domain.PROFILE),
    ("Summarize his professional experience.", Domain.PROFILE),
    ("What kind of developer is he?", Domain.PROFILE),
    ("Describe his professional background.", Domain.PROFILE),
    ("Give a short introduction about him.", Domain.PROFILE),
    ("What is his career profile?", Domain.PROFILE),

    # EDUCATION
    ("Where did he study?", Domain.EDUCATION),
    ("What is his education?", Domain.EDUCATION),
    ("Does he have a degree or diploma?", Domain.EDUCATION),
    ("Did he go to college?", Domain.EDUCATION),
    ("What did he study?", Domain.EDUCATION),

    # CERTIFICATES
    ("Does he have Java certificate?", Domain.CERTIFICATES),
    ("What certificates does he have?", Domain.CERTIFICATES),
    ("Has he completed any certification?", Domain.CERTIFICATES),
    ("Tell me about his certification?", Domain.CERTIFICATES),
    ("What is the status with his certificates?", Domain.CERTIFICATES)
]